/**
 * TagTaxonomy
 *
 * Maps raw ML Kit image labels into four semantic buckets and returns a
 * curated, prioritised selection:
 *
 *   Scene / Event   → top 2
 *   Aesthetic/Style → top 2
 *   Subject/Object  → top 3
 *   Media type      → top 1
 *
 * Input labels must already be lowercased and deduplicated.
 * They are expected to arrive sorted by confidence descending so that
 * slice(0, N) yields the top-N by confidence within each bucket.
 *
 * v2 addition: each returned label carries a `category` field mapping it
 * to one of the 9 app tag categories (people | animals | places | … | misc).
 */

import { getCategoryForTag } from '../../constants/tagCategories';

// ─── Bucket keyword lists ─────────────────────────────────────────────────────
// Matching rule: label text contains the keyword (substring match on lowercase).
// Keywords are listed most-specific first to minimise false positives.

const SCENE = [
  // Events
  'wedding',
  'party',
  'birthday',
  'graduation',
  'anniversary',
  'festival',
  'concert',
  'performance',
  'ceremony',
  'parade',
  'competition',
  'sports event',
  // Places — indoors
  'kitchen',
  'bedroom',
  'bathroom',
  'living room',
  'dining room',
  'office',
  'restaurant',
  'cafe',
  'coffee shop',
  'bar',
  'pub',
  'nightclub',
  'hotel',
  'lobby',
  'gym',
  'stadium',
  'arena',
  'court',
  'rink',
  'church',
  'temple',
  'mosque',
  'shrine',
  'cathedral',
  'airport',
  'train station',
  'bus station',
  'harbor',
  'port',
  'mall',
  'market',
  'store',
  'shop',
  'supermarket',
  'museum',
  'library',
  'gallery',
  'theater',
  'cinema',
  'classroom',
  'school',
  // Places — outdoors
  'beach',
  'desert',
  'canyon',
  'cliff',
  'valley',
  'cave',
  'island',
  'waterfall',
  'hot spring',
  'geyser',
  'mountain',
  'volcano',
  'glacier',
  'tundra',
  'forest',
  'jungle',
  'rainforest',
  'woodland',
  'savanna',
  'park',
  'garden',
  'meadow',
  'field',
  'farmland',
  'vineyard',
  'lake',
  'river',
  'pond',
  'swamp',
  'marsh',
  'ocean',
  'sea',
  'bay',
  'gulf',
  'street',
  'road',
  'highway',
  'alley',
  'plaza',
  'square',
  'bridge',
  'tunnel',
  'dam',
  'pier',
  'dock',
  'village',
  'town',
  'city',
  'downtown',
  'suburb',
  'rural',
  'urban',
  // Atmosphere / time of day
  'sunset',
  'sunrise',
  'golden hour',
  'blue hour',
  'twilight',
  'dusk',
  'dawn',
  'night',
  'nighttime',
  'fog',
  'mist',
  'storm',
  'rainbow',
  'landscape',
  'nature',
  'outdoor',
  'indoor',
  'exterior',
  'interior',
  'vacation',
  'travel',
  'trip',
  'tour',
  'holiday',
];

const AESTHETIC = [
  // Color / tone
  'black and white',
  'monochrome',
  'grayscale',
  'greyscale',
  'sepia',
  'infrared',
  'duotone',
  'toned',
  'desaturated',
  'saturated',
  'vibrant',
  'colorful',
  'pastel',
  'neon',
  'vivid',
  'muted',
  // Lighting
  'silhouette',
  'backlight',
  'rim light',
  'low light',
  'high contrast',
  'overexposed',
  'underexposed',
  'hdr',
  // Photographic style
  'bokeh',
  'depth of field',
  'long exposure',
  'double exposure',
  'multiple exposure',
  'motion blur',
  'tilt shift',
  'wide angle',
  'fish eye',
  'fisheye',
  'macro photography',
  'aerial photography',
  'astrophotography',
  'night photography',
  'street photography',
  'documentary',
  'candid',
  'flat lay',
  'overhead shot',
  "bird's eye",
  // Mood / feel
  'cinematic',
  'filmic',
  'dramatic',
  'moody',
  'atmospheric',
  'ethereal',
  'minimalist',
  'abstract',
  'surreal',
  'dreamy',
  // Texture / imperfection
  'film grain',
  'grainy',
  'vignette',
  'light leak',
  'vintage',
  'retro',
  'lo-fi',
  'analog',
  'polaroid',
  // Composition
  'symmetry',
  'symmetrical',
  'reflection',
  'mirror image',
  'leading lines',
  'rule of thirds',
  'negative space',
  'layered',
  'frame within',
  // General
  'photography',
  'artistic',
  'fine art',
  'editorial',
];

const SUBJECT = [
  // Vehicles
  'sports car',
  'race car',
  'vintage car',
  'electric car',
  'car',
  'automobile',
  'truck',
  'van',
  'bus',
  'bicycle',
  'motorbike',
  'motorcycle',
  'scooter',
  'skateboard',
  'train',
  'subway',
  'tram',
  'airplane',
  'jet',
  'helicopter',
  'drone',
  'rocket',
  'spacecraft',
  'boat',
  'sailboat',
  'ship',
  'yacht',
  'submarine',
  // Food & Drink
  'pizza',
  'burger',
  'hamburger',
  'hot dog',
  'sandwich',
  'sushi',
  'ramen',
  'pasta',
  'noodle',
  'rice',
  'soup',
  'salad',
  'steak',
  'seafood',
  'sashimi',
  'cake',
  'cupcake',
  'cookie',
  'donut',
  'pastry',
  'bread',
  'croissant',
  'ice cream',
  'chocolate',
  'candy',
  'dessert',
  'fruit',
  'berry',
  'vegetable',
  'coffee',
  'espresso',
  'latte',
  'tea',
  'juice',
  'smoothie',
  'beer',
  'wine',
  'cocktail',
  'food',
  'meal',
  'dish',
  'cuisine',
  'snack',
  'breakfast',
  'lunch',
  'dinner',
  'buffet',
  // Animals
  'golden retriever',
  'labrador',
  'bulldog',
  'poodle',
  'german shepherd',
  'dog',
  'puppy',
  'cat',
  'kitten',
  'rabbit',
  'hamster',
  'guinea pig',
  'parrot',
  'cockatiel',
  'budgie',
  'canary',
  'bird',
  'eagle',
  'owl',
  'penguin',
  'horse',
  'pony',
  'donkey',
  'cow',
  'sheep',
  'goat',
  'pig',
  'lion',
  'tiger',
  'leopard',
  'cheetah',
  'jaguar',
  'panther',
  'elephant',
  'rhino',
  'hippo',
  'giraffe',
  'zebra',
  'gorilla',
  'monkey',
  'bear',
  'polar bear',
  'wolf',
  'fox',
  'deer',
  'raccoon',
  'squirrel',
  'dolphin',
  'whale',
  'shark',
  'fish',
  'turtle',
  'frog',
  'snake',
  'lizard',
  'butterfly',
  'bee',
  'dragonfly',
  'ladybug',
  'spider',
  'insect',
  'ant',
  'animal',
  'pet',
  'wildlife',
  'fauna',
  // Music & Entertainment
  'electric guitar',
  'acoustic guitar',
  'guitar',
  'piano',
  'keyboard',
  'violin',
  'cello',
  'trumpet',
  'saxophone',
  'drums',
  'drum kit',
  'microphone',
  'musical instrument',
  'instrument',
  'music',
  // Technology
  'iphone',
  'android phone',
  'smartphone',
  'mobile phone',
  'tablet',
  'ipad',
  'laptop',
  'macbook',
  'desktop computer',
  'computer',
  'monitor',
  'keyboard',
  'gaming console',
  'playstation',
  'xbox',
  'nintendo',
  'joystick',
  'controller',
  'camera',
  'dslr',
  'mirrorless',
  'lens',
  'tripod',
  'television',
  'tv screen',
  'headphones',
  'earbuds',
  'airpods',
  'speaker',
  'microphone',
  'smartwatch',
  'fitness tracker',
  // Personal items
  'backpack',
  'handbag',
  'purse',
  'wallet',
  'suitcase',
  'luggage',
  'sunglasses',
  'glasses',
  'hat',
  'cap',
  'sneakers',
  'shoes',
  'boots',
  'heels',
  'ring',
  'necklace',
  'bracelet',
  'earring',
  'jewelry',
  'watch',
  'umbrella',
  'jacket',
  'hoodie',
  'coat',
  'dress',
  'shirt',
  't-shirt',
  'jeans',
  'clothing',
  // Books & stationery
  'book',
  'novel',
  'comic book',
  'magazine',
  'newspaper',
  'notebook',
  'diary',
  'pen',
  'pencil',
  'marker',
  // Nature — flora
  'rose',
  'tulip',
  'sunflower',
  'cherry blossom',
  'orchid',
  'lavender',
  'daisy',
  'flower',
  'plant',
  'succulent',
  'cactus',
  'fern',
  'moss',
  'mushroom',
  'palm tree',
  'oak tree',
  'pine tree',
  'tree',
  'grass',
  'leaf',
  'branch',
  // Architecture & structures
  'skyscraper',
  'apartment',
  'house',
  'villa',
  'castle',
  'palace',
  'temple',
  'building',
  'architecture',
  'tower',
  'monument',
  'statue',
  'arch',
  'dome',
  'column',
  'window',
  'door',
  'staircase',
  'balcony',
  'fence',
  'wall',
  // People
  'selfie',
  'portrait',
  'baby',
  'infant',
  'toddler',
  'child',
  'teenager',
  'woman',
  'man',
  'girl',
  'boy',
  'couple',
  'family',
  'crowd',
  'people',
  'person',
  'face',
  'human',
  'group',
  // Sports & fitness
  'basketball',
  'football',
  'soccer',
  'tennis',
  'volleyball',
  'baseball',
  'surfboard',
  'snowboard',
  'ski',
  'skateboard',
  'kayak',
  'canoe',
  'yoga',
  'exercise',
  'fitness',
  'weightlifting',
  'running',
  'cycling',
  'swimming',
  'ball',
  'racket',
  'bat',
  'glove',
  'helmet',
  // Art & decor
  'oil painting',
  'watercolor',
  'acrylic',
  'mural',
  'street art',
  'graffiti',
  'art',
  'painting',
  'sculpture',
  'drawing',
  'sketch',
  'illustration',
  'pottery',
  'ceramic',
  'vase',
  'lamp',
  'candle',
  'furniture',
  'chair',
  'sofa',
  // Natural phenomena
  'fire',
  'flame',
  'bonfire',
  'fireworks',
  'smoke',
  'lightning',
  'aurora',
  'wave',
  'splash',
  'waterfall',
];

const MEDIA = [
  // Screen content
  'screenshot',
  'screen capture',
  'screen recording',
  'screen grab',
  // Documents
  'handwriting',
  'handwritten',
  'printed text',
  'document',
  'form',
  'letter',
  'receipt',
  'invoice',
  'bill',
  'ticket',
  'boarding pass',
  'certificate',
  'diploma',
  'id card',
  'passport',
  'business card',
  // Data viz
  'pie chart',
  'bar chart',
  'line graph',
  'flowchart',
  'mind map',
  'blueprint',
  'chart',
  'graph',
  'diagram',
  'infographic',
  'table',
  'spreadsheet',
  'map',
  'floor plan',
  'schematic',
  // Digital artifacts
  'meme',
  'comic',
  'manga',
  'cartoon',
  'animation',
  'clipart',
  'qr code',
  'barcode',
  'stamp',
  'sticker',
  // Typography
  'logo',
  'wordmark',
  'icon',
  'graphic design',
  'poster design',
  'typography',
  'font',
  'text overlay',
];

// ─── Bucket classifier ────────────────────────────────────────────────────────

/**
 * Return the bucket name ('scene' | 'aesthetic' | 'subject' | 'media' | null)
 * for a single lowercased label string.
 *
 * Priority: media → scene → aesthetic → subject
 * (media is most discriminating; subject is the catch-all)
 */
function getBucket(t) {
  if (MEDIA.some(w => t === w || t.includes(w))) return 'media';
  if (SCENE.some(w => t === w || t.includes(w))) return 'scene';
  if (AESTHETIC.some(w => t === w || t.includes(w))) return 'aesthetic';
  if (SUBJECT.some(w => t === w || t.includes(w))) return 'subject';
  return null;
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Classify an array of ML Kit labels into semantic buckets and return a
 * curated selection: top 2 scene + top 2 aesthetic + top 3 subject + top 1 media.
 *
 * Each returned label includes a `category` field that maps it to one of the
 * 9 app tag categories, allowing callers to persist tags.category directly.
 *
 * @param {{ text: string, confidence: number }[]} rawLabels
 *   Labels must be lowercased and sorted by confidence descending.
 * @returns {{ text: string, confidence: number, category: string }[]}
 *   Up to 8 curated labels in bucket order. Falls back to the top 7 raw
 *   labels if the taxonomy matches nothing (e.g. very abstract imagery).
 */
export function classifyLabels(rawLabels) {
  const scene = [];
  const aesthetic = [];
  const subject = [];
  const media = [];

  for (const label of rawLabels) {
    const bucket = getBucket(label.text);
    if (bucket === 'media') media.push(label);
    else if (bucket === 'scene') scene.push(label);
    else if (bucket === 'aesthetic') aesthetic.push(label);
    else if (bucket === 'subject') subject.push(label);
  }

  const curated = [
    ...scene.slice(0, 2),
    ...aesthetic.slice(0, 2),
    ...subject.slice(0, 3),
    ...media.slice(0, 1),
  ];

  // Attach category to each label so downstream code can persist it directly.
  const addCategory = label => ({
    ...label,
    category: getCategoryForTag(label.text),
  });

  // Fallback: taxonomy matched nothing — return top raw labels so the UI
  // is never empty after a successful scan.
  return (curated.length > 0 ? curated : rawLabels.slice(0, 7)).map(
    addCategory,
  );
}

/**
 * Determine the app tag category for a single ML label text.
 * Convenience wrapper around getCategoryForTag() for callers that only need
 * the category without running the full curated-bucket pipeline.
 *
 * @param {string} labelText  lowercased label string
 * @returns {string} category key
 */
export function getCategoryForLabel(labelText) {
  return getCategoryForTag(labelText ?? '');
}
