package com.example.boxpandora.data.local.dao

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import com.example.boxpandora.data.local.entity.TagSuggestion

@Dao
interface TagSuggestionDao {
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertAll(suggestions: List<TagSuggestion>)

    @Query("SELECT * FROM tag_suggestions WHERE asset_id = :assetId")
    suspend fun getForAsset(assetId: String): List<TagSuggestion>

    @Query("DELETE FROM tag_suggestions WHERE asset_id = :assetId")
    suspend fun deleteForAsset(assetId: String)

    @Query("DELETE FROM tag_suggestions WHERE asset_id IN (:assetIds)")
    suspend fun deleteForAssets(assetIds: List<String>)

    /** Removes all suggestions for an asset generated by a specific model version. */
    @Query("DELETE FROM tag_suggestions WHERE asset_id = :assetId AND model_version = :modelVersion")
    suspend fun deleteForAssetAndModel(assetId: String, modelVersion: String)

    /** Delete all tag suggestions. Used by the "Rebuild Tag Suggestions" action. */
    @Query("DELETE FROM tag_suggestions")
    suspend fun deleteAll()

    /**
     * All pending suggestions above [minScore] that haven't been rejected or already applied,
     * across all assets. Used by SuggestionsViewModel to populate the review screen.
     */
    @Query("""
        SELECT ts.* FROM tag_suggestions ts
        WHERE ts.score >= :minScore
        AND ts.model_version = :modelVersion
        AND NOT EXISTS (
            SELECT 1 FROM tag_rejections tr
            WHERE tr.asset_id = ts.asset_id AND tr.tag_key = ts.tag_key
        )
        AND NOT EXISTS (
            SELECT 1 FROM media_tags mt
            INNER JOIN tags t ON mt.tag_id = t.id
            WHERE mt.media_uri = ts.asset_id AND t.normalized_name = ts.tag_key
        )
        ORDER BY ts.score DESC
        LIMIT :limit
    """)
    suspend fun getPendingSuggestions(
        minScore: Double,
        modelVersion: String,
        limit: Int = 300
    ): List<TagSuggestion>
}
